SE2017/urls.py
###################################################
# SE2017/urls.py: Consists of all the valid urls of SAMS-IIITS
#__authors__ = "Sri Harsha Gajavalli", "SriRamKumar", "Savitha"
#__copyright__ = "Copyright 2017, SE2017 Course"
#__Team__ = ["Sri Harsha Gajavalli", "Savitha", "SriRamKumar"]
#__license__ = "MIT"
#__version__ = "1.2"
#__maintainer__ = "SriRamKumr"
#__email__ = "sriramkumar.t15@iiits.in"
#__status__ = "Development"
####################################################


"""SE2017 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'^', include('home.urls'), name='home'),
    url(r'^login/',  auth_views.login, {'template_name': 'Login/login.html'}, name='login'),
	url(r'^logout/$', auth_views.logout, {'template_name': 'Login/login.html'}, name='logout'),
	url(r'^admin/', admin.site.urls),
    url(r'^student/', include('students.urls'), name='students'),
    url(r'^faculty/', include('faculty.urls'), name='faculty'),
    url(r'^api/',include('home.urls')),
]

if settings.DEBUG is True:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

faculty/urls.py
from django.conf.urls import url
from . import views
app_name='faculty'
urlpatterns =[	
         url(r'^ViewProfs/(\d+)/$',views.ViewProfs,name='ViewProfs'),
url(r'^ViewProfs/$',views.ViewProfs,name='ViewProfs'),
 url(r'^ViewAttendance/$',views.ViewAttendance,name='ViewAttendance'),    
url(r'^AddAssignment/$',views.AddAssignment,name='AddAssignment'),   
url(r'^ViewAssignment/$',views.ViewAssignment,name='ViewAssignment'),  
url(r'^offercourses/$',views.OfferCourses,name='OfferCourses'),  
url(r'^coursepage/$',views.CoursePage,name='CoursePage'),
url(r'^index/$',views.index,name='index'), 
url(r'^lib/$',views.MyLibrary,name='MyLibrary'),  
url(r'^details/$',views.ViewAttendanceDetails,name='ViewAttendanceDetails'),      
]

home/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'home'
urlpatterns = [
	url(r'^login/',  auth_views.login, {'template_name': 'Login/login.html'}, name='login'),
    url(r'^$', views.index, name='index'),
    url(r'^personnel/$',views.people),
    url(r'^personnel/(?P<pk>[0-9]+)/$',views.person),
    url(r'^departments/$',views.departments),
    url(r'^department/(?P<pk>[0-9]+)/$',views.department),
    url(r'^add_view_roles/',views.add_view_roles),
    url(r'^role/(?P<pk>[0-9]+)/$',views.role),
    url(r'^add_view_courses/',views.add_view_courses),
    url(r'^course/(?P<pk>[0-9]+)/$',views.course),
    url(r'^add_view_documents/',views.add_view_documents),
    url(r'^document/(?P<pk>[0-9]+)/$',views.document),
    url(r'^add_view_assignments/',views.add_view_assignments),
    url(r'^assignment/(?P<pk>[0-9]+)/$',views.assignment),
    url(r'^add_view_submissions/',views.add_view_submissions),
    url(r'^submission/(?P<pk>[0-9]+)/$',views.submission),
    url(r'^add_view_IC/',views.add_view_IC),
    url(r'^IC/(?P<pk>[0-9]+)/$',views.IC),
    url(r'^add_view_SC/',views.add_view_SC),
    url(r'^SC/(?P<pk>[0-9]+)/$',views.SC),
    url(r'^add_view_events/',views.add_view_events),
    url(r'^event/(?P<pk>[0-9]+)/$',views.event),
    url(r'^add_view_SP/',views.add_view_SP),
    url(r'^SP/(?P<pk>[0-9]+)/$',views.SP),
	url(r'^add_view_attendance/',views.add_view_attendance),
    url(r'^attendance/(?P<pk>[0-9]+)/$',views.attendance),
	url(r'^add_view_attendance_sessions/',views.add_view_attendance_sessions),
	url(r'^add_view_timetable/',views.add_view_timetable),
	url(r'^validate_user/',views.validate_user),
	url(r'^student_rel_courses/',views.student_rel_courses),
	url(r'^courses_rel_students/',views.courses_rel_students),
	url(r'^faculty_rel_courses/',views.faculty_rel_courses),
	url(r'^facultyusers/',views.faculty_users),
	url(r'^studentusers/',views.student_users),
    url(r'^student_rollno/',views.student_rollno),
    url(r'^profile/$', views.EditProfile, name='EditProfile'),
    url(r'^student_session/',views.student_session),
]

students/urls.py
from django.conf.urls import url
from . import views
app_name='students'
urlpatterns = [
        url(r'^$',views.dashboard,name='index'),
        url(r'^viewattendance/', views.viewattendance , name='ViewAttendance'),
        url(r'^assgnsubstatuspending/', views.AssgnSubStatusPending, name='AssgnSubStatusPending'),
        url(r'^assgnsubstatusoverdue/', views.AssgnSubStatusOverdue, name='AssgnSubStatusOverdue'),
        url(r'^assgnsubstatussubmitted/', views.AssgnSubStatusSubmitted, name='AssgnSubStatusSubmitted'),
        url(r'^adddropcourses/', views.addDropCourses, name='addDropCourses'),
        url(r'^events/', views.upcoming_events, name='event'),
        url(r'^register/', views.registerCourses, name='register'),
]

home/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
import json

class PersonnelForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Personnel
        fields = ('Person_ID','Role','Dept')

#Form for taking input from user for email frequency
class ProfileForm(forms.ModelForm):
	username = forms.CharField(label = 'dd')
	def __init__(self, *args, **kwargs):
		self.user = kwargs.pop('user')
		self.name = self.user.username
		super(ProfileForm, self).__init__(*args, **kwargs)
		self.fields['username'] = forms.CharField(label = 'Username',initial = self.name, disabled = 'disabled')

	class Meta:
		model = NotificationTime
		fields = ('Notification_time',)

	def save(self, commit=True):
		obj = Personnel.objects.get(LDAP_id=self.user.id)
		personID = obj.Person_ID
		personObj = Personnel.objects.get(Person_ID=personID)
		obj_ , created = NotificationTime.objects.update_or_create(Personnel_ID=personObj,defaults={'Notification_time':self.cleaned_data.get('Notification_time')})
		return obj_

home/views.py
import sys
import jwt
import datetime
from django.shortcuts import render, render_to_response
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django import template
from django.http import HttpResponse,JsonResponse
from .forms import *
from django.views.decorators.csrf import csrf_exempt
from rest_framework import exceptions,status
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from rest_framework_jwt.settings import api_settings
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import *
from .models import *
from ldif3 import LDIFParser
jwt_payload_handler = api_settings.JWT_PAYLOAD_HANDLER
jwt_encode_handler = api_settings.JWT_ENCODE_HANDLER
jwt_decode_handler = api_settings.JWT_DECODE_HANDLER

#custom decorators for JWT verification
def jwt_accept(function):
	def wrap(request, *args, **kwargs):
		try:
			token = request.META['HTTP_AUTHORIZATION'].split()[1]
		except KeyError:
			return Response({"message","No Token Found"}, status=status.HTTP_400_BAD_REQUEST)
		try:
			payload = jwt_decode_handler(token)
		except jwt.ExpiredSignature:
			return Response({"message","Signature has expired."}, status=status.HTTP_406_NOT_ACCEPTABLE)
		except jwt.DecodeError:
			return Response({"message","Error decoding signature."}, status=status.HTTP_400_BAD_REQUEST)
		except jwt.InvalidTokenError:
			return Response({"message","Invalid Token"}, status=status.HTTP_401_UNAUTHORIZED)
		return function(request, *args, **kwargs)
	wrap.__doc__=function.__doc__
	wrap.__name__=function.__name__
	return wrap

@login_required(login_url="login/")
PRIVATE_IPS_PREFIX = ('10.', '172.', '192.',)
register = template.Library()
@login_required(login_url="login/")#login credentials
def index(request):
    if request.user.personnel.Role.Role_name == "Faculty":
        return HttpResponseRedirect('../faculty/ViewProfs')
    if request.user.personnel.Role.Role_name == "Student":
        return HttpResponseRedirect('../student')
    now = datetime.datetime.now()
    remote_address = request.META.get('REMOTE_ADDR')
    # set the default value of the ip to be the REMOTE_ADDR if available
    # else None
    ip = remote_address
    # try to get the first non-proxy ip (not a private ip) from the
    # HTTP_X_FORWARDED_FOR
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        proxies = x_forwarded_for.split(',')
        # remove the private ips from the beginning
        while (len(proxies) > 0 and proxies[0].startswith(PRIVATE_IPS_PREFIX)):
            proxies.pop(0)
            # take the first ip which is not a private one (of a proxy)
        if len(proxies) > 0:
            ip = proxies[0]
    html = "IP: %s" % ip

    return render(request, "home/index.html", {'html': html, 'now': now})

@csrf_exempt
@api_view(['GET', 'POST'])
@jwt_accept
def people(request):
	"""
	List all code snippets, or create a new snippet.
	"""
	if request.method == 'GET':
		all_people = Personnel.objects.all()
		serializer = PersonnelSerializer(all_people, many=True)
		return JsonResponse(serializer.data, safe=False)

	elif request.method == 'POST':
		data = JSONParser().parse(request)
		serializer = PersonnelSerializer(data=data)
		if serializer.is_valid():
			serializer.save()
			return JsonResponse(serializer.data, status=201)
		return JsonResponse(serializer.errors, status=400)

@csrf_exempt
@api_view(['GET', 'PUT','DELETE'])
@jwt_accept
def person(request, pk):
	"""
	Retrieve, update or delete a code snippet.
	"""
	try:
		person = Personnel.objects.get(pk=pk)
	except Personnel.DoesNotExist:
		return HttpResponse(status=404)

	if request.method == 'GET':
		serializer = PersonnelSerializer(person)
		return JsonResponse(serializer.data)

	elif request.method == 'PUT':
		data = JSONParser().parse(request)
		serializer = PersonnelSerializer(person, data=data)
		if serializer.is_valid():
			serializer.save()
			return JsonResponse(serializer.data)
		return JsonResponse(serializer.errors, status=400)

	elif request.method == 'DELETE':
		person.delete()
		return HttpResponse(status=204)

@csrf_exempt
@api_view(['GET', 'POST'])
@jwt_accept
def departments(request):
	"""
	List all code snippets, or create a new snippet.
	"""
	if request.method == 'GET':
		all_departments = Department.objects.all()
		serializer = DepartmentSerializer(all_departments, many=True)
		return JsonResponse(serializer.data, safe=False)

	elif request.method == 'POST':
		data = JSONParser().parse(request)
		serializer = DepartmentSerializer(data=data)
		if serializer.is_valid():
			serializer.save()
			return JsonResponse(serializer.data, status=201)
		return JsonResponse(serializer.errors, status=400)

@csrf_exempt
@api_view(['GET', 'POST','DELETE'])
@jwt_accept
def department(request, pk):
	"""
	Retrieve, update or delete a code snippet.
	"""
	try:
		one_department = Department.objects.get(pk=pk)
	except Department.DoesNotExist:
		return HttpResponse(status=404)

	if request.method == 'GET':
		serializer = DepartmentSerializer(one_department)
		return JsonResponse(serializer.data)

	elif request.method == 'PUT':
		data = JSONParser().parse(request)
		serializer = DepartmentSerializer(one_department, data=data)
		if serializer.is_valid():
			serializer.save()
			return JsonResponse(serializer.data)
		return JsonResponse(serializer.errors, status=400)

	elif request.method == 'DELETE':
		one_department.delete()
		return HttpResponse(status=204)

@csrf_exempt
@api_view(['GET', 'POST'])
@jwt_accept
def add_view_roles(request):
	"""
	List all code snippets, or create a new snippet.
	"""
	if request.method == 'GET':
		all_roles = Roles.objects.all()
		serializer = RolesSerializer(all_roles, many=True)
		return JsonResponse(serializer.data, safe=False)

	elif request.method == 'POST':
		data = JSONParser().parse(request)
		serializer = RolesSerializer(data=data)
		if serializer.is_valid():
			serializer.save()
			return JsonResponse(serializer.data, status=201)
		return JsonResponse(serializer.errors, status=400)

@csrf_exempt
@api_view(['GET', 'POST','DELETE'])
@jwt_accept
def role(request, pk):
	"""
	Retrieve, update or delete a code snippet.
	"""
	try:
		one_role = Roles.objects.get(pk=pk)
	except Roles.DoesNotExist:
		return HttpResponse(status=404)

	if request.method == 'GET':
		serializer = RolesSerializer(one_role)
		return JsonResponse(serializer.data)

	elif request.method == 'PUT':
		data = JSONParser().parse(request)
		serializer = RolesSerializer(one_role, data=data)
		if serializer.is_valid():
			serializer.save()
			return JsonResponse(serializer.data)
		return JsonResponse(serializer.errors, status=400)

	elif request.method == 'DELETE':
		one_role.delete()
		return HttpResponse(status=204)

@csrf_exempt
@api_view(['GET', 'POST'])
@jwt_accept
def add_view_courses(request):
	"""
	List all code snippets, or create a new snippet.
	"""
	if request.method == 'GET':
		all_courses = Courses.objects.all()
		serializer = CoursesSerializer(all_courses, many=True)
		return JsonResponse(serializer.data, safe=False)

	elif request.method == 'POST':
		data = JSONParser().parse(request)
		serializer = CoursesSerializer(data=data)
		if serializer.is_valid():
			serializer.save()
			return JsonResponse(serializer.data, status=201)
		return JsonResponse(serializer.errors, status=400)

@csrf_exempt
@api_view(['GET', 'DELETE'])
@jwt_accept
def course(request, pk):
	"""
	Retrieve, update or delete a code snippet.
	"""
	try:
		one_course = Courses.objects.get(pk=pk)
	except Courses.DoesNotExist:
		return HttpResponse(status=404)

	if request.method == 'GET':
		serializer = CoursesSerializer(one_course)
		return JsonResponse(serializer.data)

	elif request.method == 'PUT':
		data = JSONParser().parse(request)
		serializer = CoursesSerializer(one_course, data=data)
		if serializer.is_valid():
			serializer.save()
			return JsonResponse(serializer.data)
		return JsonResponse(serializer.errors, status=400)

	elif request.method == 'DELETE':
		one_course.delete()
		return HttpResponse(status=204)

@csrf_exempt
@api_view(['GET', 'POST'])
@jwt_accept
def add_view_documents(request):
	"""
	List all code snippets, or create a new snippet.
	"""
	if request.method == 'GET':
		all_documents = Documents.objects.all()
		serializer = DocumentsSerializer(all_documents, many=True)
		return JsonResponse(serializer.data, safe=False)

	elif request.method == 'POST':
		data = JSONParser().parse(request)
		serializer = DocumentsSerializer(data=data)
		if serializer.is_valid():
			serializer.save()
			return JsonResponse(serializer.data, status=201)
		return JsonResponse(serializer.errors, status=400)

@csrf_exempt
@api_view(['GET', 'PUT','DELETE'])
@jwt_accept
def document(request, pk):
	"""
	Retrieve, update or delete a code snippet.
	"""
	try:
		one_document = Documents.objects.get(pk=pk)
	except Documents.DoesNotExist:
		return HttpResponse(status=404)

	if request.method == 'GET':
		serializer = DocumentsSerializer(one_document)
		return JsonResponse(serializer.data)

	elif request.method == 'PUT':
		data = JSONParser().parse(request)
		serializer = DocumentsSerializer(one_document, data=data)
		if serializer.is_valid():
			serializer.save()
			return JsonResponse(serializer.data)
		return JsonResponse(serializer.errors, status=400)

	elif request.method == 'DELETE':
		one_document.delete()
		return HttpResponse(status=204)

@csrf_exempt
@api_view(['GET','POST'])
@jwt_accept
def add_view_assignments(request):
	"""
	List all code snippets, or create a new snippet.
	"""
	if request.method == 'GET':
		all_assignments = Assignment.objects.all()
		serializer = AssignmentSerializer(all_assignments, many=True)
		return JsonResponse(serializer.data, safe=False)

	elif request.method == 'POST':
		data = JSONParser().parse(request)
		serializer = AssignmentSerializer(data=data)
		if serializer.is_valid():
			serializer.save()

home/templates/home/index.html

{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
<style>
body {
    padding-bottom: 120px;
}
</style>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>SAMS Attendance</title>

  <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   
    <link href="{% static 'home/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
<script src="{% static 'home/bootstrap/dist/js/bootstrap.min.js'%}"></script>-->

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   
    <link href="{% static 'home/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
<script src="{% static 'home/bootstrap/dist/js/bootstrap.min.js'%}"></script>

    <link href="{% static 'home/sticky-footer-navbar.css'%}" rel="stylesheet">
  </head>
  <body style="margin-bottom: 150px; margin-top:50px">


    <!-- Fixed navbar -->
   <nav class="navbar navbar-inverse navbar-fixed-top navbar-toggleable-md">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
{% block nav-course %}
          <a class="navbar-brand"  style="padding-top:0px" href="#"><img src="{% static 'images/iiits-logo.png' %}" style=" padding: 0px;height:50px"></img></a>
{% endblock %}
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#" id="home">Home</a></li>
            <li><a href="#about" id="attendace">Attendance</a></li>
            <li><a href="#contact" id= "courses">Courses</a></li>
            {% if user.personnel.Role.Role_name == "Faculty" %}  <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Assignments <span class="glyphicon glyphicon-chevron-down"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#" id="upload_assignments">Upload</a></li>
                  <li><a href="#" id="view_assignments">View</a></li>
                </ul>
              </li>

        {% else %}
	     <li><a href="#contact" id="assignments">Assignments</a></li>
       {% endif %}
	     
             <li><a href="#contact" id="events">Events</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span></a>
              <ul class="dropdown-menu">
                <li>{% if user.is_authenticated %}
<a href="#"> Hi {{ user.username }}!{% endif %}</a></li>
                <li><a href="{% url "logout" %}">Logout</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'home:EditProfile' %}">Profile Settings</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <script>
    	  Student_Home="{% url 'students:index'  %}";
          Student_Attendance="{% url 'students:ViewAttendance'  %}";
          Student_Assignments="{% url 'students:AssgnSubStatusPending' %}";
          Student_Timetable="{% url 'students:event' %}";
          Student_Courses="{% url 'students:addDropCourses' %}";


	  Faculty_Home="{% url 'faculty:ViewProfs' %}";
          Faculty_Attendance="{% url 'faculty:ViewAttendance' %}";
          Faculty_UploadAssignments="{% url 'faculty:AddAssignment' %}";
          Faculty_ViewAssignments="{% url 'faculty:ViewAssignment' %}";
          Faculty_Courses="{% url 'faculty:OfferCourses' %}";
          
          Faculty_Events="{% url 'faculty:index' %}";

	  {% if user.personnel.Role.Role_name == "Student"%}
          document.getElementById("home").setAttribute("href",Student_Home);
          document.getElementById("attendace").setAttribute("href",Student_Attendance);
          document.getElementById("assignments").setAttribute("href",Student_Assignments);
          document.getElementById("courses").setAttribute("href",Student_Courses);
          document.getElementById("events").setAttribute("href",Student_Timetable);
          {%endif%}



          {% if user.personnel.Role.Role_name == "Faculty" %}
          console.log("killllllllllllllmmmmmmmee");
          document.getElementById("home").setAttribute("href",Faculty_Home);
          document.getElementById("attendace").setAttribute("href",Faculty_Attendance);
          document.getElementById("upload_assignments").setAttribute("href",Faculty_UploadAssignments);
          document.getElementById("view_assignments").setAttribute("href",Faculty_ViewAssignments);
          document.getElementById("courses").setAttribute("href",Faculty_Courses);
          document.getElementById("events").setAttribute("href",Faculty_Events);

          {%endif%}
var jQuery_1_3_2 = $.noConflict(true);
    </script>
<div class="container">
  <br>
{% block content %}
{%  endblock %}
</div>

<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<script src="{% static 'home/bootstrap/dist/js/bootstrap.min.js'%}"></script>

 <link href="{% static 'home/sticky-footer-navbar.css'%}" rel="stylesheet">


<footer class="footer" style="position: absolute;bottom: 0px;width: 100%;text-align: center;color: white;height: 80px;background-color: #222222;">
  <a class="navbar-brand" href="#"><img src="{% static 'images/iiits-logo.png' %}" style="height:50px"></img></a>
      <div class="container">&copy; Copyright 2017 IIITS
<p>{{ html }}{% now "jS F Y H:i" %}
 </p>
      </div>
    </footer>
    <script src="{% static 'home/bootstrap/dist/js/bootstrap.min.js'%}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    

</body>

home/templates/home/profile.html
{% extends "home/index.html" %}
{% block content %}
<style>
    body {font-family: "Lato", sans-serif;}
    
    /* Style the tab */
    div.tab {
        overflow: hidden;
        border: 1px solid rgb(0, 0, 0);
        background-color: #222222;
    }
    
    /* Style the buttons inside the tab */
    div.tab button {
        background-color: inherit;
        float: left;
        border: none;
        outline: none;
        cursor: pointer;
        padding: 14px 16px;
        transition: 0.3s;
        font-size: 17px;
        color: rgb(163, 162, 162);
    }
    
    /* Change background color of buttons on hover */
    div.tab button:hover {
        background-color: rgb(148, 148, 148);
    }
    
    /* Create an active/current tablink class */
    div.tab button.active {
        background-color: rgb(7, 7, 7);
    }
    
    /* Style the tab content */
    .tabcontent {
        display: none;
        padding: 6px 12px;
        border: 1px solid #ccc;
        border-top: none;
    }
</style>
<script>window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"><\/script>')</script>
{% if messages %}
{%for message in messages %}
    <script>
    var msg="{{message}}";
    alert(msg);
     
    </script>
{%endfor%}
{%endif%}
<div class="tab">
    <button class="tablinks" id="london" onclick="openCity(event, 'London')">Email Time</button>
    <button class="tablinks" onclick="openCity(event, 'Paris')">Password</button>
  </div>
  
  <div id="London" class="tabcontent">
    <h3>Email Notification Time</h3>
    <p><form method='post'>
        {% csrf_token %}
        <table>
        {{form.as_p}}
        </table>
        <br>
        <button type="submit" name="name1" value="1">Confirm</button>
        </form></p>
  </div>
  
  <div id="Paris" class="tabcontent">
    <h3>Password Change</h3>
    <p><form method="POST">
        {% csrf_token %}
        {{form2.as_p}}
        <br>
        <button type="submit" name="name2" value="2">Change Password</button>
    </form></p> 
  </div>
  <script>
  var tablinks1 = document.getElementsByClassName("tablinks");
  tablinks1[0].className+=" active";
  document.getElementById("London").style.display = "block";
  function openCity(evt, cityName) {
      var i, tabcontent, tablinks;
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
          tabcontent[i].style.display = "none";
      }
      tablinks = document.getElementsByClassName("tablinks");
      for (i = 0; i < tablinks.length; i++) {
          tablinks[i].className = tablinks[i].className.replace(" active", "");
      }
      document.getElementById(cityName).style.display = "block";
      evt.currentTarget.className += " active";
  }
  </script>
{% endblock %}