SE2017/urls.py
###################################################
# SE2017/urls.py: Consists of all the valid urls of SAMS-IIITS
#__authors__ = "Sri Harsha Gajavalli", "SriRamKumar", "Savitha"
#__copyright__ = "Copyright 2017, SE2017 Course"
#__Team__ = ["Sri Harsha Gajavalli", "Savitha", "SriRamKumar"]
#__license__ = "MIT"
#__version__ = "1.2"
#__maintainer__ = "SriRamKumr"
#__email__ = "sriramkumar.t15@iiits.in"
#__status__ = "Development"
####################################################


"""SE2017 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'^', include('home.urls'), name='home'),
    url(r'^login/',  auth_views.login, {'template_name': 'Login/login.html'}, name='login'),
	url(r'^logout/$', auth_views.logout, {'template_name': 'Login/login.html'}, name='logout'),
	url(r'^admin/', admin.site.urls),
    url(r'^student/', include('students.urls'), name='students'),
    url(r'^faculty/', include('faculty.urls'), name='faculty'),
    url(r'^api/',include('home.urls')),
]

if settings.DEBUG is True:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'home'
urlpatterns = [
	url(r'^login/',  auth_views.login, {'template_name': 'Login/login.html'}, name='login'),
    url(r'^$', views.index, name='index'),
    url(r'^personnel/$',views.people),
    url(r'^personnel/(?P<pk>[0-9]+)/$',views.person),
    url(r'^departments/$',views.departments),
    url(r'^department/(?P<pk>[0-9]+)/$',views.department),
    url(r'^add_view_roles/',views.add_view_roles),
    url(r'^role/(?P<pk>[0-9]+)/$',views.role),
    url(r'^add_view_courses/',views.add_view_courses),
    url(r'^course/(?P<pk>[0-9]+)/$',views.course),
    url(r'^add_view_documents/',views.add_view_documents),
    url(r'^document/(?P<pk>[0-9]+)/$',views.document),
    url(r'^add_view_assignments/',views.add_view_assignments),
    url(r'^assignment/(?P<pk>[0-9]+)/$',views.assignment),
    url(r'^add_view_submissions/',views.add_view_submissions),
    url(r'^submission/(?P<pk>[0-9]+)/$',views.submission),
    url(r'^add_view_IC/',views.add_view_IC),
    url(r'^IC/(?P<pk>[0-9]+)/$',views.IC),
    url(r'^add_view_SC/',views.add_view_SC),
    url(r'^SC/(?P<pk>[0-9]+)/$',views.SC),
    url(r'^add_view_events/',views.add_view_events),
    url(r'^event/(?P<pk>[0-9]+)/$',views.event),
    url(r'^add_view_SP/',views.add_view_SP),
    url(r'^SP/(?P<pk>[0-9]+)/$',views.SP),
	url(r'^add_view_attendance/',views.add_view_attendance),
    url(r'^attendance/(?P<pk>[0-9]+)/$',views.attendance),
	url(r'^add_view_attendance_sessions/',views.add_view_attendance_sessions),
	url(r'^add_view_timetable/',views.add_view_timetable),
	url(r'^validate_user/',views.validate_user),
	url(r'^student_rel_courses/',views.student_rel_courses),
	url(r'^courses_rel_students/',views.courses_rel_students),
	url(r'^faculty_rel_courses/',views.faculty_rel_courses),
	url(r'^facultyusers/',views.faculty_users),
	url(r'^studentusers/',views.student_users),
    url(r'^student_rollno/',views.student_rollno),
    url(r'^profile/$', views.EditProfile, name='EditProfile'),
    url(r'^student_session/',views.student_session),
]

students/urls.py
from django.conf.urls import url
from . import views
app_name='students'
urlpatterns = [
        url(r'^$',views.dashboard,name='index'),
        url(r'^viewattendance/', views.viewattendance , name='ViewAttendance'),
        url(r'^assgnsubstatuspending/', views.AssgnSubStatusPending, name='AssgnSubStatusPending'),
        url(r'^assgnsubstatusoverdue/', views.AssgnSubStatusOverdue, name='AssgnSubStatusOverdue'),
        url(r'^assgnsubstatussubmitted/', views.AssgnSubStatusSubmitted, name='AssgnSubStatusSubmitted'),
        url(r'^adddropcourses/', views.addDropCourses, name='addDropCourses'),
        url(r'^events/', views.upcoming_events, name='event'),
        url(r'^register/', views.registerCourses, name='register'),
]

students/models.py
###################################################
# students/models.py:
#__author__ = ""
#__copyright__ = "Copyright 2017, SE2017 Course"
#__Team__ = ["Sri Harsha Gajavalli", "Koushik Bharadwaj", "David Christie", "Likhith Lanka", "Sajas P", "Rajeev Reddy"]
#__license__ = "MIT"
#__version__ = "1.2"
#__maintainer__ = "Likhith Lanka"
#__email__ = "likhith.l15@iiits.in"
#__status__ = "Development"
####################################################


# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

students/views.py
###################################################
# SE2017/student/views.py: Consists of all the valid methods of student module of SAMS-IIITS
#__authors__ = "David", "Sri Harsha","Sajas"
#__copyright__ = "Copyright 2017, SE2017 Course"
#__Team__ = ["Likhith", "David", "Sri Harsha","Sajas", "Koushik", "Rajeev"]
#__license__ = "MIT"
#__version__ = "1.2"
#__maintainer__ = "Likhith"
#__email__ = "likhith.l15@iiits.in"
#__status__ = "Development"
####################################################


from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils import timezone
from home.models import *
from django.core.urlresolvers import reverse


@login_required(login_url="/login/")
def dashboard(request):
    '''
    This function finds out the summary reports of attendance and Pending assignments

    '''

    user = request.user
    userPersonnelObj = Personnel.objects.filter(LDAP=user)
    MyCourses = Students_Courses.objects.filter(Student_ID=userPersonnelObj[0].Person_ID)
    CourseAttendanceContext = []
    AttendanceSessions = Attendance_Session.objects.all()

    for course in MyCourses:

        classesPresent = 0
        totalClasses = 0
        absentDays = []
        totalClassesIncurrentMonth = 0
        totalClassesPresentInCurrentMonth = 0
        for sessions in AttendanceSessions:

            if str(sessions.Course_Slot.Course_ID.Course_Name) == str(course.Course_ID):
                attendanceObject = Attendance.objects.filter(Student_ID=userPersonnelObj[0].Person_ID).filter(
                        ASession_ID=sessions.Session_ID)

                totalClasses += 1

                if (attendanceObject[0].Marked == 'P'):
                    classesPresent += 1
                    if (datetime.datetime.now().month == attendanceObject[0].Date_time.month):
                        totalClassesIncurrentMonth += 1
                        totalClassesPresentInCurrentMonth += 1


                elif (attendanceObject[0].Marked == 'A'):
                    absentDays.append(attendanceObject[0].Date_time)
                    if (datetime.datetime.now().month == attendanceObject[0].Date_time.month):
                        totalClassesIncurrentMonth += 1


        if (totalClasses == 0):
            retObj = dict(course=course, totalAttendance="N.A", monthAttendance="N.A")
        elif (totalClassesIncurrentMonth == 0):
            retObj = dict(course=course, totalAttendance=(classesPresent * 100.0 / totalClasses),
                              monthAttendance="N.A")
        else:
            retObj = dict(course=course, totalAttendance=(classesPresent * 100.0 / totalClasses),
                              monthAttendance=(totalClassesPresentInCurrentMonth * 100.0 / totalClassesIncurrentMonth))
        CourseAttendanceContext.append(retObj)
    attendanceContext = dict(CourseAttendanceContext=CourseAttendanceContext)


    pendingAssignments = []
    StudentObject = Personnel.objects.filter(LDAP=user.id)
    CoursesByStudent = Students_Courses.objects.filter(Student_ID=StudentObject[0].Person_ID)
    for course in CoursesByStudent:
        AssignmentsForCourse = Assignment.objects.filter(Course_ID=course.Course_ID.Course_ID)
        for assignment in AssignmentsForCourse:
            submissionsByStudent = Submissions.objects.filter(Assign_ID=assignment).filter(
                Student_ID=StudentObject[0].Person_ID)
            if (submissionsByStudent.count() == 0):
                now = timezone.now()
                if (assignment.End_Time > now):
                    assignContextObject = dict(Course=course, assignment=assignment)
                    pendingAssignments.append(assignContextObject)

    return render(request, "student/index.html",
                  dict(name=user, attendanceContext=attendanceContext, assignmentContext=pendingAssignments))



@login_required(login_url="/login/")
def viewattendance(request):
   
    
        user = request.user # getting data of the username
        userPersonnelObj = Personnel.objects.filter(LDAP=user) # getting the data from the table Personnel where LDAP is the username that we got earlier

        #the userPersonnelObj contains Person_ID, LDAP, Role 
        
        MyCourses = Students_Courses.objects.filter(Student_ID=userPersonnelObj[0].Person_ID)

	AttendanceSessions = Attendance_Session.objects.all()
        CourseAttendanceContext = []
        
        for course in MyCourses:
	    
	    classesPresent = 0
            totalClasses = 0
            absentDays = []
	    
            for sessions in AttendanceSessions:
		
		if str(sessions.Course_Slot.Course_ID.Course_Name) == str(course.Course_ID):
		    
                    attendanceObject = Attendance.objects.filter(Student_ID=userPersonnelObj[0].Person_ID).filter(ASession_ID=sessions.Session_ID)
		    totalClasses += 1                    

                    if (attendanceObject[0].Marked == 'P'):
                        classesPresent += 1
                    elif (attendanceObject[0].Marked == 'A'):
                        absentDays.append(attendanceObject[0].Date_time)
		
	    percent = 0
	    if totalClasses:	  
                percent = classesPresent*100/totalClasses     
	    retObj = dict(course=course, present=classesPresent, total=totalClasses, absentDays=absentDays, absent = totalClasses-classesPresent, percent=percent)
            CourseAttendanceContext.append(retObj)
	    
        context = dict(CourseAttendanceContext=CourseAttendanceContext)
    
    	return render(request, "student/ViewAttendance.html", context)  #rendering the attendance page from templates   

def AssgnSubStatusPending(request):
    '''
    function returns Pending Assignments list
    '''
    user = request.user
    pendingAssignments = []
    StudentObject = Personnel.objects.filter(LDAP=user.id)
    CoursesByStudent = Students_Courses.objects.filter(Student_ID=StudentObject[0].Person_ID)
    for course in CoursesByStudent:
        AssignmentsForCourse = Assignment.objects.filter(Course_ID=course.Course_ID.Course_ID)
        for assignment in AssignmentsForCourse:
            submissionsByStudent = Submissions.objects.filter(Assign_ID=assignment).filter(
                Student_ID=StudentObject[0].Person_ID)
            if (submissionsByStudent.count() == 0):
                now = timezone.now()
                if (assignment.End_Time > now):
                    assignContextObject = dict(Course=course, assignment=assignment)
                    pendingAssignments.append(assignContextObject)
    return render(request, 'student/AssgnSubStatusPending.html', dict(pendingAssignments=pendingAssignments))


def AssgnSubStatusOverdue(request):
    '''
    This function returns Overdue Assignments list
    '''
    user = request.user
    overdueAssignments = []
    StudentObject = Personnel.objects.filter(LDAP=user.id)
    CoursesByStudent = Students_Courses.objects.filter(Student_ID=StudentObject[0].Person_ID)
    for course in CoursesByStudent:
        AssignmentsForCourse = Assignment.objects.filter(Course_ID=course.Course_ID.Course_ID)
        for assignment in AssignmentsForCourse:
            submissionsByStudent = Submissions.objects.filter(Assign_ID=assignment).filter(
                Student_ID=StudentObject[0].Person_ID)
            if (submissionsByStudent.count() == 0):
                now = timezone.now()
                if (assignment.End_Time < now):
                    assignContextObject = dict(Course=course, assignment=assignment)
                    overdueAssignments.append(assignContextObject)
    return render(request, 'student/AssgnSubStatusOverdue.html', dict(overdueAssignments=overdueAssignments))


def AssgnSubStatusSubmitted(request):
    '''
    This function lists all the submitted Assignments
    '''
    user = request.user
    submittedAssignments = []
    StudentObject = Personnel.objects.filter(LDAP=user.id)
    CoursesByStudent = Students_Courses.objects.filter(Student_ID=StudentObject[0].Person_ID)
    for course in CoursesByStudent:
        AssignmentsForCourse = Assignment.objects.filter(Course_ID=course.Course_ID.Course_ID)
        for assignment in AssignmentsForCourse:
            submissionsByStudent = Submissions.objects.filter(Assign_ID=assignment).filter(
                Student_ID=StudentObject[0].Person_ID)
            if (submissionsByStudent.count() != 0):
                assignContextObject = dict(Course=course, assignment=assignment, submission=submissionsByStudent)
                submittedAssignments.append(assignContextObject)
    return render(request, 'student/AssgnSubStatusSubmitted.html', dict(submittedAssignments=submittedAssignments))


def addDropCourses(request):
    '''
    Just returns all the courses available for students to take
    '''
    user = request.user
    StudentObject = Personnel.objects.filter(LDAP=user.id)

    courses = Courses.objects.all()
    courseSelectionOption = []
    for course in courses:
        CourseByStudent = Students_Courses.objects.filter(Student_ID=StudentObject[0].Person_ID).filter(
            Course_ID=course.Course_ID)
        selected = True
        if CourseByStudent.count() == 0:
            selected = False
        FacultyForCourse = Instructors_Courses.objects.filter(Course_ID=course.Course_ID)
        if (FacultyForCourse.count() != 0):
            faculty = FacultyForCourse[0].Inst_ID
        else:
            faculty = "Yet To Be Decided"
        courseSelectionObj = dict(course=course, selected=selected, faculty=faculty)
        courseSelectionOption.append(courseSelectionObj)
    return render(request, 'student/CourseRegistration.html', dict(courses=courseSelectionOption))


def registerCourses(request):
    '''
    This function allows add/drop a course for a student
    '''
    
    user = request.user
    StudentObject = Personnel.objects.filter(LDAP=user.id)

students/templates/student/AssgnSubStatusOverdue.html
{% extends 'home/index.html' %}
{% block content %}


  <title>OverdueAssignments</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <!--script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script-->

<body>

<div class="container">
  <ul class="nav nav-tabs">

	<li><a data-toggle="tab" href="{% url 'students:AssgnSubStatusPending' %}">Pending Assignments</a></li>
	<li><a data-toggle="tab" href="{% url 'students:AssgnSubStatusSubmitted' %}">Submitted Assignments</a></li>
    <li class="active"><a data-toggle="tab" href="{% url 'students:AssgnSubStatusOverdue' %}">Overdue Assignments</a></li>





  </ul>
  <div class="tab-content">
    <div class="tab-pane fade in active">
		<h1>View Overdue Assignments</h1>
		<div class="row">
			<div class="col-md-2">
			</div>
			<div class="col-md-8" style="margin-top:2%">
				<div class="container-fluid">                                                                                  
					<div class="table-responsive">          
						<form action="/student/register/" method="post">
						<table class="table table-striped">
							{% csrf_token %}
							<tr>
								<th style="width: 15%"><center>AssignmentID</center></th>
								<th style="width: 45%"><center>CourseName</center></th>
								<th style="width: 40%"><center>Download</center></th>
							</tr>
							{% for k in overdueAssignments %}
							<tr>
								<td><center>{{k.assignment.Assign_ID}}</center></td>
								<td><center>{{k.Course.Course_ID}}</center></td>
								<td><center><a href={{k.assignment.Assignment_File}} id="download" download>download</a></center></td>
							</tr>
							{% endfor %}	
						</table>
					</div>
				</div>
			</div>
			<div class="col-md-2">
			</div>
		</div>
    </div>
  </div>
</div>
</body>
{% endblock %}




students/templates/student/AssgnSubStatusPending.html
{% extends 'home/index.html' %}
{% block content %}

  <title>PendingAssignments</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <!--script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->

<body>

<div class="container">
  <ul class="nav nav-tabs">
	<li class="active"><a data-toggle="tab" href="10.0.3.22:8000/student/AssgnSubStatusPending.html">Pending Assignments</a></li>
	<li><a data-toggle="tab" href="10.0.3.22:8000/student/AssgnSubStatusSubmitted.html">Submitted Assignments</a></li>
    <li><a data-toggle="tab" href="10.0.3.22:8000/student/AssgnSubStatusOverdue.html">Overdue Assignments</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane fade in active">
				<div class="page-header">
						<h1>View Pending Assignments</h1>
				</div>
		<div class="row">
			<div class="col-md-2">
			</div>
			<div class="col-md-8" style="margin-top:2%">
				<div class="container-fluid">                                                                                  
					<div class="table-responsive">          
						<form action="/student/register/" method="post">
						<table class="table table-bordered">
								<thead style="background: #333333;color:white">
							{% csrf_token %}
							<tr>
								<th style="width: 15%"><center>AssignmentID</center></th>
								<th style="width: 45%"><center>CourseName</center></th>
								<th style="width: 40%"><center>Download</center></th>
							</tr>
							</thead>
							{% for k in pendingAssignments %}
							<tr>
								<td><center>{{k.assignment}}</center></td>
								<td><center>{{k.Course.Course_ID}}</center></td>
								<td><center><a href={{k.assignment.Assignment_File}} id="download" download>download</a></center></td>
							</tr>
							{% endfor %}	
						</table>
					</div>
				</div>
			</div>
			<div class="col-md-2">
			</div>
		</div>
    </div>
  </div>
</div>
</body>
{% endblock %}




students/templates/student/AssgnSubStatusSubmitted.html
{% extends 'home/index.html' %}
{% block content %}

  <title>SubmittedAssignments</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->

<body>

<div class="container">
  <ul class="nav nav-tabs">
	<li><a data-toggle="tab" href="{% url 'students:AssgnSubStatusPending' %}">Pending Assignments</a></li>
    <li class="active"><a data-toggle="tab" href="{% url 'students:AssgnSubStatusSubmitted' %}">Submitted Assignments</a></li>
    <li><a data-toggle="tab" href="{% url 'students:AssgnSubStatusOverdue' %}">Overdue Assignments</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane fade in active">
		<h1>View Submitted Assignments</h1>
		<div class="row">
			<div class="col-md-2">
			</div>
			<div class="col-md-8" style="margin-top:2%">
				<div class="container-fluid">                                                                                  
					<div class="table-responsive">          
						<form action="/student/register/" method="post">
						<table class="table table-striped">
							{% csrf_token %}
							<tr>
								<th style="width: 15%"><center>AssignmentID</center></th>
								<th style="width: 40%"><center>CourseName</center></th>
								<th style="width: 20%"><center>Score</center></th>
								<th style="width: 25%"><center>Download</center></th>
							</tr>
							{% for k in submittedAssignments %}
							<tr>
								<td><center>{{k.assignment.Assign_ID}}</center></td>
								<td><center>{{k.Course.Course_ID}}</center></td>
								<td><center>{{k.submission.Score}}</center></td>
								<td><center><a href={{k.assignment.Assignment_File}} id="download" download>download</a></center></td>
							</tr>
							{% endfor %}	
						</table>
					</div>
				</div>
			</div>
			<div class="col-md-2">
			</div>
		</div>
    </div>
  </div>
</div>
</body>
{% endblock %}




students/templates/student/DropCourse.html
<html>

<head>

</head>

<body>


</body>
</html>

students/templates/student/ViewAttendance.html

{% extends 'home/index.html' %}
{% block content %}
   
<!--	<meta content="text/html;charset=utf-8" http-equiv="Content-Type">-->
	<meta content="utf-8" http-equiv="encoding">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <title>Attendance Register</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Raleway:400,500,800">
    <style type="text/css">
		@import url('https://fonts.googleapis.com/css?family=Open+Sans');
    	body
    	{
    		background-color:#EEE;
    		height: 100vh;
		    font-family: 'Open Sans';
		    font-size:2vh;
		    overflow-x:hidden;
		    color:#555;
    	}
    	p
    	{
    		font-family: 'Open Sans';
		    font-size:3vh;
		    overflow-x:hidden;
		    color:#555;

    	}
    	.info-box
    	{
    		background-color:#DDD;
    		height: :30vh;
    	}
	   .panel-head {
    background-color: #00A5F2;
    color: #fff;
    margin-left: -3%;
    width: 106%;
		   padding: 10px 10px;}
    </style>

<body>


	<div id="absent-days" class="modal fade" role="dialog">
  		<div class="modal-dialog">
    		<div class="modal-content">
      			<div class="modal-header">
        			<button type="button" class="close" data-dismiss="modal">&times;</button>
   				 	<h4 class="modal-title">Absent Days</h4>
 			 	</div>
      			<div class="modal-body">
    				<ul id="modal-content">
                        
    				</ul>
     			</div>
  				<div class="modal-footer">
        			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      			</div>
			 </div>

  		</div>
	</div>
       
	<div class="row">
		<div class="col-md-12 ">
			<h1>Attendace Register</h1>
			
		 	

			
	

			<div class="info-box col-md-4" style="width:100vh;height:60vh; position: relative; margin:0px aut; margin-right: auto; margin-left: aut" >



				<br />

				<table class="table table-striped table-hover">
					 <tr>
						 <th>Course</th>
                   		 <th>Number of Classes</th>
						 <th>Present</th>
                    	 <th>Absent</th>
						 <th>Percentage</th>
						 <!--<th>Absent Days</th>-->
                	</tr>
					{% for i in CourseAttendanceContext %}
						<tr>

							<td>{{ i.course.Course_ID.Course_Name }}</td>
							<td>{{i.total}}</td>
							<td>{{i.present}}</td>

                            <td>{{i.absent}}</td>
                            <td>{{i.percent}}</td>
                            <!--<td><button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#absent-days">Absent days</button></td>
							--><!--<script>
								var total="{{i.total}}";
								var present="{{i.present}}";
                                var absentDay=[];
                                var temp=0;
								{% for k in i.absentDays %}
            						absentDay[temp].push("{{k}}");
            					{% endfor %}
                                
                                
								var absent=(parseInt(total)-parseInt(present));
								var percent=(parseInt(present)/parseInt(total));
								document.getElementById("absent").innerHTML = absent;
								document.getElementById("percent").innerHTML = percent;
								document.getElementById("modal-content").innerHTML=createModal();
								function createModal(){
                					var text = "";
                					for (j = 0; j < absentDay[temp].length;j++) {
                   						 text +="<li>"+absentDay[temp][j]+"</li>"+"<br>";
               						 }
               						 return text;
           						 }
                                 temp=temp+1;
							</script>-->
							
						</tr>
					{% endfor %}
					</table>
			</div>
		</div>
        
	<script
              src="https://code.jquery.com/jquery-3.2.1.js"
              integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
              crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
{% endblock %}

students/templates/student/events.html
{% extends 'home/index.html' %}


<!DOCTYPE html>
<html lang="en">
<head>
  <title>Upcoming Events</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <div class="tab-content">
    <div class="tab-pane fade in active">
		<div class="row">
			<div class="col-md-2">
			</div>
			<div class="col-md-8" style="margin-top:2%">
				<div class="container-fluid">
					<div class="table-responsive">
						<form action="/student/register/" method="post">
						<table class="table table-striped">
							{% csrf_token %}
							<tr>
								<th style="width: 15%"><center>EventID</center></th>
								<th style="width: 45%"><center>Event Name</center></th>
								<th style="width: 40%"><center>Event Date</center></th>
							</tr>
							{% for k in events %}
							<tr>
								<td><center>{{k.event.Event_ID}}</center></td>
								<td><center>{{k.event.Event_Name}}</center></td>
								<td><center>{{k.event.Event_Date}}</center></td>
							</tr>
							{% endfor %}
						</table>
					</div>
				</div>
			</div>
			<div class="col-md-2">
			</div>
		</div>
    </div>
  </div>
</div>
</body>
</html>