SE2017/urls.py
###################################################
# SE2017/urls.py: Consists of all the valid urls of SAMS-IIITS
#__authors__ = "Sri Harsha Gajavalli", "SriRamKumar", "Savitha"
#__copyright__ = "Copyright 2017, SE2017 Course"
#__Team__ = ["Sri Harsha Gajavalli", "Savitha", "SriRamKumar"]
#__license__ = "MIT"
#__version__ = "1.2"
#__maintainer__ = "SriRamKumr"
#__email__ = "sriramkumar.t15@iiits.in"
#__status__ = "Development"
####################################################


"""SE2017 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'^', include('home.urls'), name='home'),
    url(r'^login/',  auth_views.login, {'template_name': 'Login/login.html'}, name='login'),
	url(r'^logout/$', auth_views.logout, {'template_name': 'Login/login.html'}, name='logout'),
	url(r'^admin/', admin.site.urls),
    url(r'^student/', include('students.urls'), name='students'),
    url(r'^faculty/', include('faculty.urls'), name='faculty'),
    url(r'^api/',include('home.urls')),
]

if settings.DEBUG is True:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

faculty/urls.py
from django.conf.urls import url
from . import views
app_name='faculty'
urlpatterns =[	
         url(r'^ViewProfs/(\d+)/$',views.ViewProfs,name='ViewProfs'),
url(r'^ViewProfs/$',views.ViewProfs,name='ViewProfs'),
 url(r'^ViewAttendance/$',views.ViewAttendance,name='ViewAttendance'),    
url(r'^AddAssignment/$',views.AddAssignment,name='AddAssignment'),   
url(r'^ViewAssignment/$',views.ViewAssignment,name='ViewAssignment'),  
url(r'^offercourses/$',views.OfferCourses,name='OfferCourses'),  
url(r'^coursepage/$',views.CoursePage,name='CoursePage'),
url(r'^index/$',views.index,name='index'), 
url(r'^lib/$',views.MyLibrary,name='MyLibrary'),  
url(r'^details/$',views.ViewAttendanceDetails,name='ViewAttendanceDetails'),      
]

home/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'home'
urlpatterns = [
	url(r'^login/',  auth_views.login, {'template_name': 'Login/login.html'}, name='login'),
    url(r'^$', views.index, name='index'),
    url(r'^personnel/$',views.people),
    url(r'^personnel/(?P<pk>[0-9]+)/$',views.person),
    url(r'^departments/$',views.departments),
    url(r'^department/(?P<pk>[0-9]+)/$',views.department),
    url(r'^add_view_roles/',views.add_view_roles),
    url(r'^role/(?P<pk>[0-9]+)/$',views.role),
    url(r'^add_view_courses/',views.add_view_courses),
    url(r'^course/(?P<pk>[0-9]+)/$',views.course),
    url(r'^add_view_documents/',views.add_view_documents),
    url(r'^document/(?P<pk>[0-9]+)/$',views.document),
    url(r'^add_view_assignments/',views.add_view_assignments),
    url(r'^assignment/(?P<pk>[0-9]+)/$',views.assignment),
    url(r'^add_view_submissions/',views.add_view_submissions),
    url(r'^submission/(?P<pk>[0-9]+)/$',views.submission),
    url(r'^add_view_IC/',views.add_view_IC),
    url(r'^IC/(?P<pk>[0-9]+)/$',views.IC),
    url(r'^add_view_SC/',views.add_view_SC),
    url(r'^SC/(?P<pk>[0-9]+)/$',views.SC),
    url(r'^add_view_events/',views.add_view_events),
    url(r'^event/(?P<pk>[0-9]+)/$',views.event),
    url(r'^add_view_SP/',views.add_view_SP),
    url(r'^SP/(?P<pk>[0-9]+)/$',views.SP),
	url(r'^add_view_attendance/',views.add_view_attendance),
    url(r'^attendance/(?P<pk>[0-9]+)/$',views.attendance),
	url(r'^add_view_attendance_sessions/',views.add_view_attendance_sessions),
	url(r'^add_view_timetable/',views.add_view_timetable),
	url(r'^validate_user/',views.validate_user),
	url(r'^student_rel_courses/',views.student_rel_courses),
	url(r'^courses_rel_students/',views.courses_rel_students),
	url(r'^faculty_rel_courses/',views.faculty_rel_courses),
	url(r'^facultyusers/',views.faculty_users),
	url(r'^studentusers/',views.student_users),
    url(r'^student_rollno/',views.student_rollno),
    url(r'^profile/$', views.EditProfile, name='EditProfile'),
    url(r'^student_session/',views.student_session),
]

faculty/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

faculty/views.py
###################################################
# SE2017/views.py: Consists of all the valid methods of faculty module of SAMS-IIITS
#__authors__ = "Vagdevi Kommineni", "Swathi Reddy", "Sonia","Indrojyothi Mondal"
#__copyright__ = "Copyright 2017, SE2017 Course"
#__Team__ = ["Vagdevi Kommineni", "Swathi Reddy", "Sonia","Indrojyothi Mondal"]
#__license__ = "MIT"
#__version__ = "1.2"
#__maintainer__ = "Vagdevi"
#__email__ = "vagdevi.k15@iiits.in"
#__status__ = "Development"
####################################################


from __future__ import unicode_literals

import json
import datetime

from dateutil.parser import parse
from django.contrib.auth.decorators import login_required
from django.shortcuts import *
from home.serializers import *



@login_required
def index(request):
	all_events = Events.objects.all()
	serializer = EventsSerializer(all_events, many=True)
	a=[]
	for i in serializer.data:
		a.append({"title":i["Event_Name"],"start":i["Event_Date"],"allDay":True})
	#print serializer.data
	return render(request, 'fullcalendar/calendar.html',{"Events":json.dumps(a)})


@login_required	

def ViewProfs(request):

    

    CourseList = []
    if request.GET.get('hint'):
	hint=request.GET.get('hint')
    else:
        hint=2
    if request.user.personnel.Role.Role_name == 'Faculty':
        request.session['Prof_Name'] = request.user.username
        person_id = request.user.personnel.Person_ID
        IC = Instructors_Courses.objects.all()
        for i in range(0, len(IC)):
            if person_id == IC[i].Inst_ID.Person_ID:
                CourseList.append(IC[i].Course_ID.Course_Name)
        if CourseList == []:
            flag = 0

        else:
            flag = 1
    template = loader.get_template('prof.html')

    context = {'flag':flag,'Courses':CourseList,'Prof_Name':request.session['Prof_Name'],'hint':hint}

    return HttpResponse(template.render(context, request))


@login_required
def CoursePage(request):

	if request.POST.get('action')=='Save':

		course=Courses.objects.get(Course_Name=request.session['course'])
		course.Course_description = request.POST.get('coursedes')
        	course.save()

	else:
		request.session['course'] =request.POST.get('dropdown')
	course=get_object_or_404(Courses,Course_Name=request.session['course'])
    	template = loader.get_template('prof1.html')
    	context = {'Course':course,'CourseName':request.session['course']}
    	return HttpResponse(template.render(context, request))



@login_required
def AddAssignment(request):
    
    success=0
    if request.method == 'POST':
        
  	date_joined =datetime.datetime.now()
	if parse(request.POST.get('enddate'))>=date_joined:
		courses = Courses.objects.all()
		for corse in courses:
			if corse.Course_Name == request.session['course']:
		            course = Courses.objects.get(Course_Name=corse.Course_Name)
		            break
		instance = Assignment(Course_ID=course, Assignment_File=request.FILES['file'],End_Time=request.POST.get('enddate'))
		instance.save()
	    	success=1
	else:
		success=2
	return render(request, 'forms.html',{'CourseName':request.session['course'],'success':success})

    else:
		CourseList=[]
		person_id = request.user.personnel.Person_ID
        	IC = Instructors_Courses.objects.all()
        	for i in range(0, len(IC)):
            		if person_id == IC[i].Inst_ID.Person_ID:
                		CourseList.append(IC[i].Course_ID.Course_Name)

		if 'course' in request.session:

			success=0
    			return render(request, 'forms.html',{'CourseName':request.session['course'],'s':success})
		elif 'course' not in request.session and CourseList==[] :
			return redirect(reverse('faculty:ViewProfs')+"?flag=0&hint=1")
		else:
			return redirect(reverse('faculty:ViewProfs')+"?hint=0")


@login_required
def ViewAssignment(request):
     
     asslist = []
     CourseList = []
     Assignments = Assignment.objects.all()
     person_id = request.user.personnel.Person_ID
     IC = Instructors_Courses.objects.all()
     for i in range(0, len(IC)):
     	if person_id == IC[i].Inst_ID.Person_ID:
        	CourseList.append(IC[i].Course_ID.Course_Name)
     for assignment in Assignments:
	if 'course' in request.session:
     		if assignment.Course_ID.Course_Name ==request.session['course'] and assignment.End_Time.date()!=datetime.datetime.strptime('1900-01-01',"%Y-%m-%d").date():
			print assignment.Assignment_File
			asslist.append(assignment)
	elif 'course' not in request.session and CourseList==[]:
		return redirect(reverse('faculty:ViewProfs')+"?flag=0&hint=1")
	else:
		return redirect(reverse('faculty:ViewProfs')+"?hint=0")
     return render(request, 'assignment.html', {'Assignments': asslist,'CourseName':request.session['course']})
  

@login_required    

def OfferCourses(request):
    """
        Displays a table of course offerings
        value:  The request to be processed (request)
          
        """
    if request.method == 'POST':
        person_id = request.user.personnel.Person_ID
        person = Personnel.objects.get(Person_ID=person_id)
        courseids = request.POST.getlist('courses[]')
        for cid in courseids:
            corse = Courses.objects.get(Course_ID=cid)
            IC = Instructors_Courses(Course_ID=corse, Inst_ID=person, Start_Date='2017-1-1', End_Date='2017-1-1')
            IC.save()

	return redirect(reverse('faculty:OfferCourses'))


    else:
        IC = Instructors_Courses.objects.all()
        IClist = []
        courselist = []
        for ic in IC:
            IClist.append(ic.Course_ID)
        person_id = request.user.personnel.Person_ID
        courses = Courses.objects.all()
        courses1 = []
        for corse in courses:
            if corse not in IClist:
                courses1.append(corse)
        for course in courses:
            courselist.append(course.Course_ID)
            courselist.append(course.Course_Name)

        template = loader.get_template('reg.html')
        context = {'Courses': courses1, 'Courses1': json.dumps(courselist), 'IC': IC,
                   'Prof_Name': request.user.username}
        return HttpResponse(template.render(context, request))


@login_required
def ViewAttendance(request):

	"""
        Displays a table of session-wise attendance of students for the session course.
        value:  The request to be processed (request)
        Returns:  'attendance.html' (template), a dictionary containing sessions,CourseName(dictionary)
        """
	sessionlist={}
	sessions=Attendance_Session.objects.all()
	students=Attendance.objects.all()
	CourseList=[]
	person_id = request.user.personnel.Person_ID
        IC = Instructors_Courses.objects.all()
        for i in range(0, len(IC)):
        	if person_id == IC[i].Inst_ID.Person_ID:
                	CourseList.append(IC[i].Course_ID.Course_Name)
	for session in sessions:
		if 'course' in request.session:
			if session.Course_Slot.Course_ID.Course_Name==request.session['course']:
				sessionlist[session.Session_ID]=[session.Date_time.date,0]
		elif 'course' not in request.session and CourseList==[]:
			return redirect(reverse('faculty:ViewProfs')+"?flag=0&hint=1")
		else:
			return redirect(reverse('faculty:ViewProfs')+"?hint=0")
	for session in sessionlist:
		for student in students:
			if session==student.ASession_ID.Session_ID and student.Marked=='P':
				sessionlist[session][1]=sessionlist[session][1]+1
    	template = loader.get_template('attendance.html')
    	context = {'sessions':sessionlist,'CourseName':request.session['course']}
    	return HttpResponse(template.render(context, request))
@login_required
def ViewAttendanceDetails(request):
	"""
        Displays a table of assignments along with the respective deadlines for the session course.
        value:  The request to be processed
        Returns:  'details.html' template, a dictionary containing students object, CourseName , date
        """
	slotid=request.GET.get('id')
	session=Attendance_Session.objects.get(Session_ID=slotid)
	students=Attendance.objects.all()
	studentlist=[]
	for student in students:
		if str(student.ASession_ID.Session_ID)==str(slotid):
			studentlist.append(student)
	template = loader.get_template('details.html')
    	context = {'students':studentlist,'CourseName':request.session['course'],'date':session.Date_time.date}
    	return HttpResponse(template.render(context, request))


@login_required
def MyLibrary(request):

    """
        Displays the upload button to upload files.If POST method, then processes the request and appends the uploaded file to the table.
        value:  The request to be processed (request)
        Returns:  'lib.html' template, a dictionary containing asslist,CourseName,success
    """
    success=0
    libfiles=[]
    if request.method == 'POST':
		courses = Courses.objects.all()
		libfiles=request.FILES.getlist("files")
		for corse in courses:
			if corse.Course_Name == request.session['course']:
				course = Courses.objects.get(Course_Name=corse.Course_Name)
				break
		for libfile in libfiles:
			instance = Assignment(Course_ID=course, Assignment_File=libfile,Start_Time=datetime.datetime.now(),End_Time='1900-01-01')
			instance.save()
		success=1
		asslist = []
		Assignments = Assignment.objects.all()
		for ass in Assignments:
			if ass.Course_ID.Course_Name ==request.session['course'] and ass.End_Time.date()==datetime.datetime.strptime('1900-01-01',"%Y-%m-%d").date():
				asslist.append(ass)
		return render(request, 'lib.html',{'MyLibList':asslist,'CourseName':request.session['course'],'success':success})



    else:
		asslist = []
		success=0
		Assignments = Assignment.objects.all()
		for assignment in Assignments:
			if assignment.Course_ID.Course_Name ==request.session['course'] and assignment.End_Time.date()==datetime.datetime.strptime('1900-01-01',"%Y-%m-%d").date():
				asslist.append(assignment)
		return render(request, 'lib.html',{'MyLibList':asslist,'CourseName':request.session['course'],'success':success})

faculty/templates/assignment.html
{% extends "home/index.html" %}
{% block content %}
<style>
.abc{
background-color:black;
color:white !important;
}
h3,h2{
font-family:"Times New Roman";
}
h5{
font-family:"Times New Roman";
text-decoration:none;
color:black;
}
#tab{
margin-top:55px;
position:absolute;
top:100px;
left:50px;
}
.panel-body{
  background:#e3e5e8;
}
</style><br>
<div class="btn-group" role="group" aria-label="...">
        <button type="button" class="btn btn-default" id="deadlines" >Deadlines</button>
        <button type="button" class="btn btn-default" id="clicked1"  >My Library</button>
</div>
<div class="panel panel-default">
        <div class="panel-heading" style="background:#222222;color:white; align:left;">
                {{CourseName}} Assignment Deadlines
        </div>
<div class="panel-body"><center>
<script type="text/javascript">
    document.getElementById("deadlines").onclick = function () {
        location.href = "{% url 'faculty:ViewAssignment' %}";
    };
document.getElementById("clicked1").onclick = function () {
        location.href = "{% url 'faculty:MyLibrary' %}";
    };
</script>
<br>

{% if Assignments %}
<table id="tblSample" class="table table-bordered" style="background:white; width:80%;">
<thead style="background: #333333;color:white">
<tr>
  <th>Assignment</th>
<th>Deadline</th>
</tr>
</thead>
<tbody>
{% for document in Assignments %}
<tr>
    <td><a href="{{document.Assignment_File.url}}" target="_blank"><h5><b>{{ document.Assignment_File.name|slice:"18:" }}</b></h5></a></td>
    <td><h5><b>{{document.End_Time.date}}</b></h5></td>
</tr>
    {% endfor %}
</tbody>
</table>

{% else %}
<h1 style="color:red;">OOPS! No documents</h1> 
{% endif %}
</center>
</div>
</div>
{% endblock %}

faculty/templates/attendance.html
{% extends "home/index.html" %}
{% block content %}

<style>
.panel-body{
  background:#e3e5e8;
}
h3,h2{
font-family:"Times New Roman";
}
</style>
<div class="panel panel-default">
  <div class="panel-heading" style="background:#222222;color:white; align:left;">
    {{CourseName}} Attendance
  </div>
  <div class="panel-body"><center>
<table id="tblSample" class="table table-bordered" style="background:white; width:80%;">
<thead style="background: #333333;color:white">
<tr>
  <th>Session Date</th>
<th>Students Present</th>
 </tr>
</thead>
<tbody>
{% for key,value in sessions.items %}
<tr>
<td>{{value.0}}</td>
<td><a  href="../details?id={{key}}">{{value.1}}</a></td>
</tr>
{% endfor %}
</tbody>
</table>
</center>
</div>
</div>
<script>
</script>
{% endblock %}

faculty/templates/course_page.html
:{% extends 'home/index.html' %}
{% block content %}

<center><h3>Choose Course </h3></center><br>

<center>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
<select  name="dropdown">	
{% for course in Courses %}

<option value="{{course}}" > {{course}}</option>

{% endfor %}
</select><br><br>
        <input type="submit" value="Submit" type="submit" class="btn btn-success">
    </form></center>

{% endblock %}

faculty/templates/lib.html
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
{% extends "home/index.html" %}
{% load static %}
{% load faculty_extras %}
{% block content %}

<style>
.abc{
background-color:black;
color:white !important;
}
#tab{

position:absolute;
top:100px;
left:50px;
}
h5{
font-family:"Times New Roman";
text-decoration:none;
color:black;
}
h3,h2{
font-family:"Times New Roman";
}
div#left {
    width:15%;
    float:left;
}
.file {
    visibility: hidden;
    position: absolute;
  }
  .file{
margin-left:15px;
}
.upload{
position:relative;
right:40px;
}

#main{
width:1000px;

text-align:center;
}
#main div{
display:inline-block;
}
.panel-body{
  background:#e3e5e8;
}
</style>
<br>
<p id="demo"></p>
<script>
var r={{success}};
if(r==1){
	var t='<div class="alert alert-success"> <strong>Successfully Uploaded!</strong></div>';
	document.getElementById("demo").innerHTML=t;
	window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 3000);
}
</script>

<div class="btn-group" role="group" aria-label="...">
        <button type="button" class="btn btn-default" id="deadlines" >Deadlines</button>
        <button type="button" class="btn btn-default" id="clicked1"  >My Library</button>
      </div>
      <div class="panel panel-default">
            <div class="panel-heading" style="background:#222222;color:white; align:left;">
                    {{CourseName}} Library
            </div>
    <div class="panel-body">
<script type="text/javascript">
    document.getElementById("deadlines").onclick = function () {
        location.href = "{% url 'faculty:ViewAssignment' %}";
    };
document.getElementById("clicked1").onclick = function () {
        location.href = "{% url 'faculty:MyLibrary' %}";
    };
    $(document).on('click', '.browse', function(){
          var file = $(this).parent().parent().parent().find('.file');
          file.trigger('click');
        });
        $(document).on('change', '.file', function(){
          $(this).parent().find('.form-control').val($(this).val().replace(/C:\\fakepath\\/i, ''));
        });
</script>
<form action="{% url 'faculty:MyLibrary' %}" method="post" enctype="multipart/form-data">
    <!--{% csrf_token %}
      <input type="file"  id="file" onchange="this.form.submit()" name='files' multiple />
      </form></center>-->
      {% csrf_token %}
      <div class="form-group">
              File:<input type="file" class="file" onchange="this.form.submit()"  name="files" multiple required >
              <div class="input-group col-xs-12">
            <span class="input-group-addon"><i class="glyphicon glyphicon-folder-open"></i></span>
            <input type="text" class="form-control input-lg" disabled placeholder="Upload File">
            <span class="input-group-btn">
              <button class="browse btn btn-primary input-lg" type="button"><i class="glyphicon glyphicon-search"></i> Browse</button>
            </span>
          </div>
      </div>
  </form>
  <center>
{% if MyLibList %}

<table id="tblSample" class="table table-bordered" style="background:white; width:80%;">
<thead style="background: #333333;color:white">

<th width="50%">File Name</th>
<th width="20%">Size</th>
<th>Uploaded On</th>
</thead>
{% for document in MyLibList %}
<tr >
<td><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD7SeZ_d0TQKBXnwh2JEl3BPErckP2H9sdR5XfqlOOw8CoiJ8l" alt="{{ document.Assignment_File.name }}" width="20" height="20" border="1"><a href="{{document.Assignment_File.url}}" target="_blank"><b><span style="color:black;font-family:Times New Roman;">{{ document.Assignment_File.name|slice:"18:" }}</span></b></a></td>

<td width="20%">{{ document.Assignment_File.size|multiply:0.000001}} MB</td>


<td>{{ document.Start_Time}}</td>
</tr>


    {% endfor %}
</table>

{% endif %}
</center>
</div>
</div>
    {% endblock %}

faculty/templates/navbar.html
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
{% block link %}
{% endblock %}

{% block head %}
{% endblock %}
</head>
<style>
.nav > li > a:hover{
	background-color: #000099;
}

</style>

<div class="fluid-container">
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse abc">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
{% block core %}
  <a class="navbar-brand" id="navcourse" href="{% url 'faculty:CoursePage' %}">Navbar</a>
{% endblock %}
  <div class="collapse navbar-collapse main" id="navbarSupportedContent">
    <ul class="nav navbar-nav mr-auto">
	<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle abc active" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
          Assignments
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'faculty:AddAssignment' %}">Upload</a>
          <a class="dropdown-item" href="{% url 'faculty:Delass' %}">View</a>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link active" href="{% url 'faculty:ViewAttendance' %}" >Attendance</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'faculty:index' %}" >Students</a>
      </li>
	<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle abc active" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
          Schedules
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Time Table</a>
          <a class="dropdown-item" href="#">Almanac</a>
        </div>
      </li>
	<li class="nav-item">
        <a class="nav-link active" href="{% url 'faculty:OfferCourses' %}">Offer Courses</a>
      </li>
    </ul>
  </div>
</nav>
{% block addcontent %}
{% endblock %}


</div>

faculty/templates/prof.html
{% extends "home/index.html" %}
{% load static %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<style>

#offer{
background-color:black!important;
color:white !important;
border-radius:10px;
width:15%;
font-size:20px;
font-family:"Times New Roman";
height:40px;
}
h3{
font-family:"Times New Roman";
}
</style>

{% if flag == 0 %}
<center>
<button id="offer"  >Offer Courses</button></center>
<script type="text/javascript">
    document.getElementById("offer").onclick = function () {
        location.href = "{% url 'faculty:OfferCourses' %}";
    };
</script>
{% elif hint == '0'  %}
<script>
alert('Please Select A Course');
</script>
<center>
<h3><b>Please Select A Course </b></h3>
<form action="{% url 'faculty:CoursePage' %}"  method="post" enctype="multipart/form-data">
  {% csrf_token %}
<div class="form-group">
<select name="dropdown" class="form-control" onchange="this.form.submit()" id="sub" required>
<option  value="" selected="selected"  hidden>--select--</option>
{% for course in Courses %}
<option value="{{course}}" > {{course}}</option>
{% endfor %}
</select><br><br>
</div>
</form>
</center>
{% elif hint == '1' and flag == '0' %}
<center>
<button id="offer"  >Offer Courses</button></center>
<script type="text/javascript">
    document.getElementById("offer").onclick = function () {
        location.href = "{% url 'faculty:OfferCourses' %}";
    };
</script>

{% else %}
<center>
<h3><b>Please Select A Course </b></h3>
<form action="{% url 'faculty:CoursePage' %}"  method="post" enctype="multipart/form-data">
  {% csrf_token %}
<div class="form-group">
<select name="dropdown" class="form-control" onchange="this.form.submit()" id="sub" required>
<option  value="" selected="selected"  hidden>--select--</option>
{% for course in Courses %}
<option value="{{course}}" > {{course}}</option>
{% endfor %}
</select><br><br>
</div>
</form>
</center>
{% endif %}
{% endblock %}